export const SET_ONE_PRODUCT = "SET_ONE_PRODUCT"
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS"
export const SET_CATEGORIES = "SET_CATEGORIES"
export const SET_PRODUCTS_BY_CATEGORIES = "SET_PRODUCTS_BY_CATEGORIES"
